### ISSUE TITLE
Question regarding normal from depth

### ISSUE THREAD

**Issue by YuxuanSnow** [mbaradad/depth_prompt#1]
Hi,

amazing work, very inspiring and interesting!

I have a question regarding the normal calculation from depth map. I wonder why you don't simply calculate the normal via the image gradient of depth map, but calculate it from the unprojected depth point cloud? Did you observe some issue with the normal from depth image gradient? I ask this because calculating image gradient is simpler than the current implementation.

Thanks!

**Comment by mbaradad** [comment]
Yes, you are right. Using the gradients of depth z instead of 3D normals may yield similar results (as this is an extra regularization term), although using explicitly the 3D normals typically produces more appealing 3D results when looking at the 3D pointclouds. For example, for planar surfaces, the cosine similarity between all the pixels is 1, while the z-gradient will depend on the orientation of the camera. This makes planar surfaces (which are an important part of all scenes)  be better predicted with 3D normals than with z-gradient. Still, we did not compare our approach against using z-gradients, and different datasets/evaluation tasks may perform better. 

Furthermore, computing the normals is not that costly in practice, as we compute them with the nearby pixels and not k-nearest neighbors (which produces better estimates).
